### ISSUE TITLE
Change TimeSet

### ISSUE THREAD

**Issue by Bluesens** [inflop/Countimer#1]
Hi. I really find usefull this library, intuitive and easy to implement. But I want to change the time, I´m working on arduino, and can´t get to the function to do so. It´s preseted on setup, but I wanted to change it on the way, on void loop, preseting with a potenciometer the minutes for example. I will appreciate any help. Thank´s.

**Comment by inflop** [comment]
You can do this by calling setCounter() method while counter already running.
Try this example -> [sketch_feb04a.txt](https://github.com/inflop/Countimer/files/117932/sketch_feb04a.txt)

**Comment by Bluesens** [comment]
I resolver it already but i maybe an interesting code to manage the clock
with only one potenciómeter. Later sentí it to you... Maybe can be useful.
Thanks. Best regalos.
David
