### ISSUE TITLE
Change Time with Push Button

### ISSUE THREAD

**Issue by eXplOiD1** [inflop/Countimer#2]
Hello i want to use your libary to set up a changeble timer but i have a problem the time will be changed in the serial print but if i start the timer it dosent work the timer is still standing.

here my code i realy hope you can help me i like your timer much.

```
// Includes
#include <Countimer.h>
// Includes

Countimer timer1;

long int timerup = 0;
long int timer = 0;
int startbutton = 0;
int secounds = 0;
int minutes = 0;

void setup() {
  // put your setup code here, to run once:
Serial.begin(9600);
pinMode(2, INPUT);
pinMode(3, INPUT);


timer1.setCounter(0, 0, 0, timer1.COUNT_DOWN, output);
timer1.setInterval(output, 1000);

}

void loop() {
  // put your main code here, to run repeatedly:

startbutton = digitalRead(3);
timerup = digitalRead(2);

if (timerup == 1)
  {
  delay (70);
  secounds++;
  }

if (secounds >= 60)
  {
    minutes++;
    secounds = 0;
  }

timer1.setCounter(0, minutes, secounds);

timer1.run();
timer = timer1.getCurrentSeconds();

if (startbutton == 1)
{
  timer1.start();
}
else if (startbutton == 0)
{
  timer1.pause();
}

Serial.println(timer1.getCurrentTime());

}

void output() {
  Serial.print("timer : ");
  Serial.println(timer1.getCurrentTime());
}
```

**Comment by ad015** [comment]
Hi 
i don't know why you setup the timer as  ( timer1 ) not (timer) are you planing to run more than one timer ? i dont know this lib can do  this ?  

any way try 
to add 
timer1.run();

after 
void loop() {

i know its old post but many some have same problem .

Nice work ... working grate...
but give me replay if this lib can run more than timer.
for ex.
2 timer for tow relay.

**Comment by eXplOiD1** [comment]
Ye the lib can run many more counters today i can give you an example if i are home from work
