### ISSUE TITLE
isCounterRunning() not working?

### ISSUE THREAD

**Issue by code-al** [inflop/Countimer#7]
I'm trying to use this function but it isn't recognized. Help?

**Comment by inflop** [comment]
Oh yes, it's not implemented yet ;) Try use `!isStopped() && !isCounterCompleted()` condition at this moment. Let me know if it helps.

**Comment by code-al** [comment]
Yes, im currently using isStopped as alternative. Thanks

**Comment by dbcom** [comment]
Hi! 
Great job on the timer.

Would the below code work as a quick and dirty workaround for **isCounterRunning**?

// Returns true if counter is still running, otherwise returns false.
	bool isCounterRunning();

void Countimer::isCounterRunning()
{
	// timer is running only if is not completed or not stopped.
	if (_isCounterCompleted || _isStopped) return (**true**);
	return (**false**);
)

**Comment by inflop** [comment]
@dbcom, try this:
```cpp
// Returns true if counter is still running, otherwise returns false.
void Countimer::isCounterRunning() {
    // timer is running only if is not completed and not stopped.
    return !_isCounterCompleted && !_isStopped;
}

**Comment by dbcom** [comment]
Thanks!
